### ISSUE TITLE
Early 2008 Macbook Pro with notorious driver glitch, should this work?

### ISSUE THREAD

**Issue by MrMormon** [hakzsam/archlive-nouveau#6]

**Comment by pierremoreau** [comment]
Which graphic cards does your 2008 MBP have? If it has a 9400M (NVAC/MCP79), it was fixed in kernel 3.19. If it has a 9600M GT (NV96/G96), the fix has just been pulled by Nouveau's maintainer and should be included in kernel 4.4 (maybe even earlier, not sure about that).
If you have neither of those GPUs, do you have a link to one bug report describing your issues, or could you write them here please?

**Comment by MrMormon** [comment]
I'm pretty sure it's a [Macbook Pro 4.1 Penryn](https://support.apple.com/kb/SP4), early 2008, 15.4 inch, NVIDIA GeForce 8600M GT graphics processor with dual-link DVI support; 256MB of GDDR3 memory on 2.4GHz configuration.

I can't find anything about what my lousy memory told me was an infamous graphics glitch, but I just realized I need to reinstall rEFInd.
